[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.7"
version_files = [
    "gcp_secretmanager_cache/_version.py:__version__",
    "pyproject.toml:version"
]
tag_format = "$version"
